@api = http://localhost:3000/products


GET {{api}}

### Create a product 

POST {{api}} 
# crear un dato hay que enviar un objecto json
Content-Type: application/json

{
    "name": "GPU",
    "description": "RX 500",
    "quantity": 20
}


### Getting a product by ID
GET {{api}}/5

### Deleting a product
DELETE {{api}}/9

### Get total products
GET {{api}}/count

### Update product
PUT {{api}}/4
Content-Type: application/json

{
    "name": "Mousepad",
    "description": "Ryzer Mousepad",
    "quantity": 100
}